server:
  port: 8080
  
spring:  neo4j:    uri:  bolt://localhost/7474
    authentication:      username: neo4j
      password: Hilix12!
      
  application:    name: NEO-WAREHOUSE-SERVICE
